# =====================
# SERVER
# =====================
server.port=8083
server.error.include-stacktrace=never

# =====================
# JWT
# =====================
jwt.secret=CAMBIAR_ESTA_CLAVE_SUPER_LARGA_Y_SEGURA_2026

# =====================
# LOGS
# =====================
logging.level.root=INFO

# =====================
# FILE UPLOAD LIMIT
# =====================
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB