jwt.secret=administracionzonal_super_secret_key_2026_segura_32chars
spring.datasource.url=jdbc:postgresql://localhost:5432/azvch
spring.datasource.username=postgres
spring.datasource.password=Quito2025*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=administracionzonal
spring.jpa.properties.hibernate.format_sql=true
server.port=8083

